maximized = true
no-multigrid = false
tabs = true
wsl = false

[font]
normal = [
        "IosevkaTermSlab Nerd Font",
        "Noto Color Emoji",
]
size = 14.0
edging = "subpixelantialias"

[font.features]
"IosevkaTermSlab Nerd Font" = [
        # Disable ligatures
        "-calt",
]
