[mgr]
count_copied   = { fg = "black", bg = "green" }
count_cut      = { fg = "black", bg = "red" }
count_selected = { fg = "black", bg = "yellow" }

[tabs]
active   = { bg = "blue", fg = "black", bold = true }
inactive = { fg = "blue", bg = "black" }

[mode]
normal_main = { bg = "blue", fg = "black", bold = true }
normal_alt  = { fg = "blue", bg = "black" }
select_main = { bg = "red",  fg = "black", bold = true }
select_alt  = { fg = "red",  bg = "black" }
unset_main  = { bg = "red",  fg = "black", bold = true }
unset_alt   = { fg = "red",  bg = "black" }

[icon]
prepend_dirs = [
        { name = ".git",      text = "", fg = "#f54d27" },
        { name = "Documents", text = "", fg = "#85ea2d" },
        { name = "Dotfiles",  text = "", fg = "#85ea2d" },
        { name = "Downloads", text = "", fg = "#85ea2d" },
        { name = "Games",     text = "󰺶", fg = "#85ea2d" },
        { name = "Library",   text = "", fg = "#85ea2d" },
        { name = "Music",     text = "", fg = "#85ea2d" },
        { name = "Pictures",  text = "", fg = "#85ea2d" },
        { name = "Projects",  text = "", fg = "#85ea2d" },
        { name = "Videos",    text = "", fg = "#85ea2d" },
]
prepend_files = [
        { name = ".exrc",       text = "", fg = "#019833" },
        { name = ".nvimrc",     text = "", fg = "#019833" },
        { name = "maskfile.md", text = "", fg = "#6d8086" },
]
prepend_exts = [
        { name = "lemon",     text = "", fg = "#ddd06a" },
        { name = "love",      text = "󰋑", fg = "#ff5faf" },
        { name = "msgpack",   text = "", fg = "#eca517" },
        { name = "ron",       text = "󰠮", fg = "#dea584" },
        { name = "xxd",       text = "", fg = "#019833" },
        { name = "zc",        text = "", fg = "#dea584" },
]
prepend_conds = [
        { if = "link", text = "", fg = "#6d8086" },
]
